package vista;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.MateriaDAO;
import rol_escolar.Materia;

public class RegistroMaterias extends javax.swing.JFrame {
    
    public RegistroMaterias() {
        initComponents();
        cargarTablaMaterias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TituloMaterias = new javax.swing.JLabel();
        cve_materia = new javax.swing.JLabel();
        nombre_materia = new javax.swing.JLabel();
        TextBox_nombre_materia = new java.awt.TextField();
        vigente = new javax.swing.JLabel();
        rb_vigente_SI = new javax.swing.JRadioButton();
        rb_vigente_NO = new javax.swing.JRadioButton();
        btn_actualizar = new javax.swing.JButton();
        btn_registrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btn_listarTodas = new javax.swing.JButton();
        spinner_Clave = new javax.swing.JSpinner();
        TablaMaterias = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Menu = new javax.swing.JMenuBar();
        inicio = new javax.swing.JMenu();
        InicioMenu = new javax.swing.JMenuItem();
        RegistroProfesores = new javax.swing.JMenu();
        RegistroAlumnos = new javax.swing.JMenu();
        AlumnosMenu = new javax.swing.JMenuItem();
        RegistroMaterias = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloMaterias.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TituloMaterias.setText("REGISTRO DE MATERIAS");

        cve_materia.setText("Clave Materia");

        nombre_materia.setText("Nombre de Materia");

        TextBox_nombre_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBox_nombre_materiaActionPerformed(evt);
            }
        });

        vigente.setText("¿Vigente?");

        rb_vigente_SI.setText("SI");
        rb_vigente_SI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_vigente_SIActionPerformed(evt);
            }
        });

        rb_vigente_NO.setText("NO");
        rb_vigente_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_vigente_NOActionPerformed(evt);
            }
        });

        btn_actualizar.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_registrar.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btn_listarTodas.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        btn_listarTodas.setText("Listar Todas");
        btn_listarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarTodasActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaMaterias.setViewportView(jTable1);

        inicio.setText("Inicio");

        InicioMenu.setText("Página Principal");
        InicioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioMenuActionPerformed(evt);
            }
        });
        inicio.add(InicioMenu);

        Menu.add(inicio);

        RegistroProfesores.setText("Registro Profesores");
        Menu.add(RegistroProfesores);

        RegistroAlumnos.setText("Registro Alumnos");

        AlumnosMenu.setText("Alumnos");
        AlumnosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlumnosMenuActionPerformed(evt);
            }
        });
        RegistroAlumnos.add(AlumnosMenu);

        Menu.add(RegistroAlumnos);

        RegistroMaterias.setText("Registro Materias");
        Menu.add(RegistroMaterias);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloMaterias)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nombre_materia)
                                    .addComponent(cve_materia)
                                    .addComponent(vigente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextBox_nombre_materia, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(rb_vigente_SI)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_vigente_NO))
                                    .addComponent(spinner_Clave)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_registrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_listarTodas, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(TablaMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TituloMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cve_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinner_Clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(nombre_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TextBox_nombre_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vigente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_vigente_SI)
                            .addComponent(rb_vigente_NO))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_listarTodas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(TablaMaterias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextBox_nombre_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBox_nombre_materiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBox_nombre_materiaActionPerformed

    private void rb_vigente_SIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_vigente_SIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_vigente_SIActionPerformed

    private void rb_vigente_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_vigente_NOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_vigente_NOActionPerformed

    private void cargarTablaMaterias() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Clave");
        modelo.addColumn("Nombre");
        modelo.addColumn("Vigente");

        MateriaDAO materia_dao = new MateriaDAO();
        List<Materia> lista = materia_dao.listarTodo();

        for (Materia m : lista) {
            Object[] fila = {
                m.getCve_materia(),
                m.getNombre_materia(),
                m.getVigente()
            };
            modelo.addRow(fila);
        }

        jTable1.setModel(modelo);
    }
    
    private void btn_listarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarTodasActionPerformed
        MateriaDAO dao = new MateriaDAO();
        java.util.List<Materia> materias = dao.listarTodo();
        
        StringBuilder sb = new StringBuilder();
        for (Materia m : materias) {
            sb.append(m.mostrarMateria()).append("\n");
        }
        
        if (materias.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay materias registradas.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, sb.toString(), 
                "Listado de Materias", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        cargarTablaMaterias();
    }//GEN-LAST:event_btn_listarTodasActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        int clave = (int) spinner_Clave.getValue();
        String nombre = TextBox_nombre_materia.getText();
        String vigente ="";
        
        if(rb_vigente_SI.isSelected() && rb_vigente_NO.isSelected()){
            JOptionPane.showMessageDialog(this, "Seleccione solo una opción (Si o No).");
        } else if(rb_vigente_SI.isSelected()){
            vigente = rb_vigente_SI.getText();
        } else {
            vigente = rb_vigente_NO.getText();
        }
        
        if (clave == 0 || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
            return;
        }
        Materia materia = new Materia(clave, nombre, vigente);
        MateriaDAO dao = new MateriaDAO();
        
        if (dao.insertarMateria(materia)) {
            JOptionPane.showMessageDialog(this, "Materia registrada correctamente.");
            spinner_Clave.setValue(0);
            TextBox_nombre_materia.setText("");
            buttonGroup1.clearSelection();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar la materia.");
        }
        cargarTablaMaterias();
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        MateriaDAO dao = new MateriaDAO();
        int clave = (int) spinner_Clave.getValue();
        
        if (dao.eliminarMateria(clave)) {
            JOptionPane.showMessageDialog(this, "Materia con clave " + clave + " eliminada correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar materia");
        }
        cargarTablaMaterias();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        int clave = (int) spinner_Clave.getValue();
        String nombre = TextBox_nombre_materia.getText();
        String vigente ="";
        
        if(rb_vigente_SI.isSelected() && rb_vigente_NO.isSelected()){
            JOptionPane.showMessageDialog(this, "Seleccione solo una opción (Si o No).");
        } else if(rb_vigente_SI.isSelected()){
            vigente = rb_vigente_SI.getText();
        } else {
            vigente = rb_vigente_NO.getText();
        }
        
        if (clave == 0 || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
            return;
        }
        Materia materia = new Materia(clave, nombre, vigente);
        MateriaDAO dao = new MateriaDAO();
        
        if (dao.actualizarMateria(materia)) {
            JOptionPane.showMessageDialog(this, "Materia con clave " + clave + " actualizada correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar materia");
        }
        cargarTablaMaterias();
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void InicioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioMenuActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InicioMenuActionPerformed

    private void AlumnosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlumnosMenuActionPerformed
        RegistroEstudiantes estudiantes = new RegistroEstudiantes();
        estudiantes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AlumnosMenuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroMaterias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlumnosMenu;
    private javax.swing.JMenuItem InicioMenu;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu RegistroAlumnos;
    private javax.swing.JMenu RegistroMaterias;
    private javax.swing.JMenu RegistroProfesores;
    private javax.swing.JScrollPane TablaMaterias;
    private java.awt.TextField TextBox_nombre_materia;
    private javax.swing.JLabel TituloMaterias;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_listarTodas;
    private javax.swing.JButton btn_registrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cve_materia;
    private javax.swing.JMenu inicio;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nombre_materia;
    private javax.swing.JRadioButton rb_vigente_NO;
    private javax.swing.JRadioButton rb_vigente_SI;
    private javax.swing.JSpinner spinner_Clave;
    private javax.swing.JLabel vigente;
    // End of variables declaration//GEN-END:variables
}
